# Generated by Django 4.1.1 on 2024-10-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('cuil', models.CharField(max_length=11)),
                ('ingresoTrabajo', models.DateField()),
                ('sueldo', models.FloatField(max_length=50)),
                ('jornadaLaboral', models.CharField(max_length=2)),
                ('alta', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('razonSocial', models.CharField(max_length=50)),
                ('rama', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('relacion', models.PositiveSmallIntegerField(choices=[(0, 'Cónyuge'), (1, 'Hijo/a')])),
                ('vinculante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='afiliados.afiliado')),
            ],
            bases=('personas.rol',),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.comercio'),
        ),
    ]
