# Generated by Django 4.1.1 on 2022-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='estadoCivil',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Casado'), (1, 'Viudo'), (2, 'Soltero'), (3, 'Divorciado')]),
        ),
    ]
