# Generated by Django 4.1.1 on 2022-11-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
