# Generated by Django 4.1.3 on 2022-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cuil',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
