# Generated by Django 4.1.1 on 2024-10-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senia', models.FloatField()),
                ('reserva', models.DateField()),
                ('inicio', models.DateField()),
                ('monto', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('pago_senia', models.DateField(blank=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('capacidad', models.PositiveIntegerField()),
                ('monto', models.FloatField(max_length=9)),
                ('imagen', models.ImageField(null=True, upload_to='static/img')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('descripcion', models.TextField(null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('afiliado', models.ManyToManyField(through='salones.Alquiler', to='afiliados.afiliado')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('precio', models.FloatField()),
                ('obligatorio', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon')),
            ],
        ),
        migrations.CreateModel(
            name='PagoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pago', models.DateField(blank=True, null=True)),
                ('numero', models.IntegerField(default=1)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.alquiler')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon'),
        ),
    ]
