# Generated by Django 4.1.1 on 2022-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='monto',
            field=models.FloatField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoalquiler',
            name='monto',
            field=models.FloatField(max_length=9),
        ),
    ]
