# Generated by Django 4.1.1 on 2024-10-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
