# Generated by Django 4.1.1 on 2024-10-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_salon_descripcion_salon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='senia',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PagoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.alquiler')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuotas', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pago', models.DateField()),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.alquiler')),
            ],
        ),
    ]
