# Generated by Django 4.1.1 on 2022-10-31 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('encargado', models.BooleanField()),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVinculo', models.PositiveSmallIntegerField(choices=[(0, 'Conyuge'), (1, 'Hijo'), (2, 'Tutor')])),
                ('vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculados', to='personas.persona')),
                ('vinculante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculantes', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[])),
                ('desde', models.DateTimeField(auto_now_add=True)),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='personas.persona')),
            ],
        ),
    ]
