# Generated by Django 4.1.1 on 2024-10-12 00:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estadoCivil', models.PositiveSmallIntegerField(choices=[(0, 'Casado/a'), (1, 'Viudo/a'), (2, 'Soltero/a'), (3, 'Divorciado/a')], null=True)),
                ('domicilio', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('es_afiliado', models.BooleanField(default=False)),
                ('es_alumno', models.BooleanField(default=False)),
                ('es_profesor', models.BooleanField(default=False)),
                ('es_encargado', models.BooleanField(default=False)),
                ('es_familiar', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(3, 'profesor'), (2, 'alumno'), (1, 'afiliado'), (5, 'familiar')])),
                ('desde', models.DateField(default=datetime.datetime.now)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='personas.persona')),
            ],
        ),
    ]
