# Generated by Django 4.1.1 on 2022-11-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='familia',
            field=models.ManyToManyField(blank=True, through='personas.Vinculo', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(3, 'profesor'), (2, 'alumno'), (1, 'afiliado')]),
        ),
    ]
