# Generated by Django 4.1.1 on 2022-11-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_familia_alter_rol_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='desde',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
