# Generated by Django 4.1.1 on 2022-11-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='desde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
