# Generated by Django 4.1.1 on 2024-10-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('cupo', models.PositiveIntegerField(help_text='Cupo minimo de alumnos para iniciar dictado')),
                ('modulos', models.PositiveIntegerField(help_text='Cantidad de horas. 1 modulo = 1 hora')),
                ('tipoModulo', models.PositiveSmallIntegerField(choices=[(0, 'Por clase'), (1, 'Por mes'), (2, 'Total')])),
                ('descuento', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('formaPago', models.PositiveSmallIntegerField(choices=[(0, 'Clase'), (1, 'Mensual')])),
            ],
        ),
        migrations.CreateModel(
            name='Dictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('cupo', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('area', models.PositiveSmallIntegerField(choices=[(0, 'Capacitacion'), (1, 'Cultura'), (2, 'Gimnasio')])),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('aniosExperiencia', models.PositiveIntegerField()),
                ('cbu', models.PositiveIntegerField(unique=True)),
                ('especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.especialidad')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Titularidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulares', to='cursos.dictado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictados', to='cursos.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='PagoDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DateField()),
                ('monto', models.FloatField(max_length=10)),
                ('tipoPago', models.PositiveSmallIntegerField(choices=[(0, 'Debito'), (1, 'Credito'), (2, 'Efectivo')])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.dictado')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidacion', models.DateField()),
                ('monto', models.FloatField()),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.titularidad')),
            ],
        ),
        migrations.AddField(
            model_name='dictado',
            name='profesores',
            field=models.ManyToManyField(through='cursos.Titularidad', to='cursos.profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.especialidad'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.dictado')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.DateField()),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='cursos.titularidad')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dictado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.dictado'),
        ),
    ]
