# Generated by Django 4.1.1 on 2022-11-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dictado',
            field=models.ManyToManyField(blank=True, through='cursos.PagoDictado', to='cursos.dictado'),
        ),
    ]
