# Generated by Django 4.1.1 on 2022-11-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
    ]
