# Generated by Django 4.1.1 on 2022-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='añosExperiencia',
            new_name='aniosExperiencia',
        ),
        migrations.AddField(
            model_name='profesor',
            name='cbu',
            field=models.PositiveIntegerField(default=0, max_length=22),
            preserve_default=False,
        ),
    ]
