# Generated by Django 4.1.1 on 2022-11-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_alumno_dictado'),
        ('cursos', '0002_remove_profesor_domicilio_remove_profesor_telefono'),
    ]

    operations = [
    ]
