# Generated by Django 4.1.3 on 2022-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_alumno_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictado',
            old_name='aula',
            new_name='aulas',
        ),
        migrations.RenameField(
            model_name='dictado',
            old_name='profesor',
            new_name='profesores',
        ),
        migrations.AlterField(
            model_name='aula',
            name='numero',
            field=models.PositiveIntegerField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cbu',
            field=models.PositiveIntegerField(max_length=22, unique=True),
        ),
    ]
