# Generated by Django 4.1.1 on 2022-11-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_rename_aula_dictado_aulas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictado',
            name='aulas',
        ),
        migrations.AddField(
            model_name='dictado',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='cursos.titularidad'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.dictado'),
        ),
        migrations.AlterField(
            model_name='titularidad',
            name='dictado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulares', to='cursos.dictado'),
        ),
        migrations.AlterField(
            model_name='titularidad',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictados', to='cursos.profesor'),
        ),
    ]
